### ISSUE TITLE
sctransformV2 usage across datasets

### ISSUE THREAD

**Issue by Nusob888** [saketkc/scRNA_NB_comparison#3]
Hi, 

I enjoyed reading the paper. I was hoping to clarify one aspect, which unfortunately is difficult to deduce from the code. 

It is stated in the paper:

"While this approach successfully identifies DE genes within a single dataset, even when cell populations vary in their sequencing depth, it generates a high proportion of false positives when performing differential expression across datasets that have been normalized independently. **We reasoned that performing differential expression on corrected UMI counts across datasets** (see the “[Methods] section) could alleviate this problem."

Highlighted is the bit I am confused about. 

Am I right in interpreting this to state that sctransformv2 should be applied across all datasets in preference to performing individual dataset normalisation?

```{r}
##Across individual datasets - example 1
obj_list <- lapply(obj_list, function(x){SCTransform(x, vst.flavor = "v2"})
combined <- merge(obj_list[[1]], obj_list[2:length(obj_list)])


##Across all datasets - example 2
combined <- merge(obj_list[[1]], obj_list[2:length(obj_list)])
combined <- SCTransform(combined, vst.flavor = "v2")
````

Here, in the above options would example 2 be preferable prior to DEG testing?

Many thanks in advance

**Comment by saketkc** [comment]
We recommend applying SCTransform on each dataset independently. During the UMI correction step, the model uses median UMI (for a dataset) to calculate the corrected counts. If there are two datasets with very high difference in sequencing depths, we choose the minimum of the two median sequencing depth to calculate the corrected counts before running DE. If you perform DE on pearson residuals (across these two datasets) - they will likely have too many false positives because they might be on different scales.

You can see an example of this workflow in the [v2 vignette](https://satijalab.org/seurat/articles/sctransform_v2_vignette.html) - the correction is done by `PrepSCTFindMarkers`.

**Comment by Nusob888** [comment]
Brilliant, thanks for the swift response. This makes sense.
